apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sreconfig
  namespace: sre
spec:
  channel: alpha
  name: sreconfig
  source: sre-operators
  installPlanApproval: Manual
